package io.framemind.modules.scriptmind.agent;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.framemind.agent.config.AgentDefinition;
import io.framemind.agent.orchestration.AgentCallAdapter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.function.Consumer;

/**
 * World Builder agent: constructs the story bible and world setting
 * based on the outline generated by the Showrunner.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class WorldBuilderAgent {

    private final AgentCallAdapter agentCallAdapter;
    private final ObjectMapper objectMapper;

    /**
     * Build a story bible / world setting from the given outline.
     *
     * @param outline   the structured outline (ScriptContent JSON)
     * @param onChunk   streaming callback for partial output
     * @return a JsonNode containing the world bible
     */
    public JsonNode buildWorld(JsonNode outline, Consumer<String> onChunk) {
        log.info("WorldBuilderAgent building world from outline");

        String prompt = buildWorldPrompt(outline);
        AgentDefinition definition = new AgentDefinition(
                "world_builder",
                "你是一位专业的世界观架构师（World Builder），负责为影视剧本构建完整、一致的世界观设定。"
                        + "你需要设定时代背景、地理环境、社会规则、权力结构和文化体系。"
                        + "请始终以 JSON 格式输出，确保世界观与故事大纲完美契合。",
                4
        );

        try {
            String response = agentCallAdapter.call(definition, prompt, onChunk);
            return objectMapper.readTree(response);
        } catch (Exception e) {
            log.error("WorldBuilderAgent failed to build world", e);
            return buildFallbackWorldBible(outline);
        }
    }

    // ─── Prompt Builder ─────────────────────────────────────────────

    private String buildWorldPrompt(JsonNode outline) {
        return String.format("""
                请根据以下故事大纲构建完整的世界观设定（故事圣经）。

                ## 故事大纲
                %s

                ## 输出格式要求
                请严格按照以下 JSON schema 输出：

                {
                  "setting": "总体设定描述（时代、地域、社会背景）",
                  "time_period": "故事发生的时间段",
                  "locations": [
                    {
                      "name": "地点名称",
                      "description": "地点描述",
                      "significance": "在故事中的重要性",
                      "atmosphere": "氛围描述"
                    }
                  ],
                  "rules": {
                    "power_structure": "权力结构描述",
                    "social_hierarchy": "社会层级",
                    "economic_system": "经济体系",
                    "cultural_norms": "文化规范",
                    "taboos": "禁忌与底线"
                  },
                  "timeline": [
                    {
                      "event": "关键事件",
                      "relative_time": "相对时间（如 -2年, 0, +3月）",
                      "impact": "对故事的影响"
                    }
                  ],
                  "themes": ["核心主题1", "核心主题2"],
                  "tone": "整体基调",
                  "visual_style": "视觉风格描述"
                }

                ## 要求
                1. 世界观必须与大纲中的情节逻辑一致
                2. 为每个主要场景提供详细的地点设定
                3. 建立清晰的规则体系（即使在现实题材中也需明确社会规则）
                4. 时间线要支撑起完整的叙事弧线
                5. 请只输出 JSON，不要包含额外说明
                """,
                outline.toString());
    }

    // ─── Fallback Builder ───────────────────────────────────────────

    private JsonNode buildFallbackWorldBible(JsonNode outline) {
        var root = objectMapper.createObjectNode();
        root.put("setting", "现代都市 -- 一线城市");
        root.put("time_period", "当代");

        var locations = objectMapper.createArrayNode();
        var loc1 = objectMapper.createObjectNode();
        loc1.put("name", "主要场景");
        loc1.put("description", "待详细设定");
        loc1.put("significance", "故事主要发生地");
        loc1.put("atmosphere", "待定");
        locations.add(loc1);
        root.set("locations", locations);

        var rules = objectMapper.createObjectNode();
        rules.put("power_structure", "待设定");
        rules.put("social_hierarchy", "待设定");
        rules.put("economic_system", "待设定");
        rules.put("cultural_norms", "待设定");
        rules.put("taboos", "待设定");
        root.set("rules", rules);

        root.set("timeline", objectMapper.createArrayNode());

        var themes = objectMapper.createArrayNode();
        themes.add("成长");
        themes.add("冲突与和解");
        root.set("themes", themes);

        root.put("tone", "待定");
        root.put("visual_style", "待定");

        return root;
    }
}
